# Generated by Django 2.1.2 on 2018-10-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipAirline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipairline_id', models.IntegerField()),
                ('passenger_numb', models.IntegerField()),
            ],
        ),
    ]
